# Generated by Django 4.1.1 on 2022-09-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_options_user_company_user_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
